export const advocacyCopy = {
  hubTitle: 'ADVOCACY',
  hubSubtitle: 'Shining a light on game-used cards.',
  hubDescription:
    'Follow evidence-backed efforts to improve transparency, authenticity, and accountability across the hobby.',
  researchLine: 'Research protects collectors. Evidence improves the hobby.',
  mwVsAdvocacyTip:
    'Most Wanted solves one specific card. Advocacy documents a wider pattern — transparency, counterfeits, provenance, or record corrections — with linked evidence.',
  myAdvocacy: 'MY ADVOCACY',
  submitIssue: 'SUBMIT AN ISSUE',
  search: 'SEARCH',
  empty: 'No initiatives in this filter yet.',
  loadError: 'Could not load initiatives.',
  featured: 'FEATURED INITIATIVE',
  activeAlerts: 'ACTIVE COLLECTOR ALERTS',
  transparencyStandards: 'TRANSPARENCY AND STANDARDS',
  gatheringEvidence: 'GATHERING EVIDENCE',
  recentOutcomes: 'RECENT OUTCOMES',
  howItWorks: 'HOW ADVOCACY WORKS',
  howBody:
    'Education identifies a problem. Database and Most Wanted provide examples. Discussion analyzes. Advocacy organizes evidence and requests change. Outcomes become part of the public record.',
  viewInitiative: 'VIEW INITIATIVE',
  followUpdates: 'FOLLOW UPDATES',
  unfollow: 'UNFOLLOW',
  submitEvidence: 'SUBMIT EVIDENCE',
  joinDiscussion: 'JOIN DISCUSSION',
  share: 'SHARE',
  withdraw: 'WITHDRAW SUPPORT',
  youSupported: 'You support this initiative',
  youFollowing: 'You follow updates',
  signInToAct: 'Sign in to take action',
  whatHappening: 'What is happening?',
  whyMatters: 'Why does it matter?',
  changeRequested: 'What change is requested?',
  evidence: 'EVIDENCE',
  timeline: 'TIMELINE',
  related: 'RELATED',
  relatedPrimary: 'Primary subject',
  relatedAffected: 'Affected items',
  relatedEvidence: 'Supporting evidence',
  relatedResearch: 'Related research',
  relatedDiscussion: 'Discussion',
  showAllAffected: 'Show all',
  showFewerAffected: 'Show fewer',
  outcome: 'OUTCOME REPORT',
  sources: 'SOURCES',
  updates: 'UPDATES',
  myTitle: 'MY ADVOCACY',
  mySubtitle: 'Initiatives you support or follow.',
  myEmpty: 'You have not supported or followed any initiatives yet.',
  submitIssueTitle: 'SUBMIT AN ISSUE',
  submitIssueHint:
    'Submissions enter admin review. They are not published as accusations. A single unauthenticated card usually belongs in Most Wanted unless it shows a wider pattern.',
  submitEvidenceTitle: 'SUBMIT EVIDENCE',
  submitted: 'Submitted for review.'
};
