export const cardDetailCopy = {
  evidenceConfidence: 'EVIDENCE CONFIDENCE',
  wguRating: 'WGU Rating',
  wguExplanation: 'Expert review score from the authentication team.',
  communityRating: 'Community Rating',
  communityExplanation: 'Average research vote from signed-in collectors.',
  finalScore: 'Final Score',
  finalExplanation: 'Combined trust signal from expert and community ratings.',
  confidenceLow: 'Low confidence',
  confidenceFair: 'Fair confidence',
  confidenceGood: 'Good confidence',
  confidenceHigh: 'High confidence',
  confidenceNone: 'Not yet rated',
  notRated: 'Not rated',
  votes: (n: number) => `${n} vote${n === 1 ? '' : 's'}`,
  signInToRate: 'Sign in to add your research vote.',
  yourVote: 'Your vote',
  actionEvidence: 'Evidence',
  actionCompare: 'Compare',
  actionDiscussion: 'Discussion',
  actionHistory: 'History',
  cardInformation: 'CARD INFORMATION',
  provenance: 'PROVENANCE / SOURCE',
  evidenceHighlights: 'EVIDENCE HIGHLIGHTS',
  relatedCards: 'RELATED CARDS',
  discussionPreview: 'DISCUSSION PREVIEW',
  noRelated: 'No related catalog cards found yet.',
  noDiscussion: 'No active discussion threads yet.',
  viewDiscussion: 'VIEW DISCUSSION',
  sourceCatalog: 'Catalog reference',
  sourceAuthenticated: 'Authenticated copies on file',
  sourcePublished: 'Published to database',
  shareMessage: (title: string) => `Research this card on Which Game Used: ${title}`,
  unauthenticated: 'UNVERIFIED',
  authenticated: 'AUTHENTICATED'
} as const;
