export const databaseCopy = {
  searchPlaceholder: 'Player, team, year, set…',
  searchTitle: 'Browse database',
  featuredEmpty: 'No authenticated cards in the catalog yet.',
  recentEmpty: 'No catalog cards yet. Check back after the team publishes records.',
  viewAll: 'VIEW ALL',
  authenticatedCopies: 'Authenticated copies',
  noAuthenticatedCopies: 'No authenticated copies yet for this card.',
  authCount: (n: number) => (n === 1 ? '1 authenticated copy' : `${n} authenticated copies`),
  requestCardTitle: 'Request to add',
  requestCardSubtitle: 'Tell us about the card so we can add it to the database.',
  requestSubmit: 'SUBMIT REQUEST',
  requestSuccess: 'Request submitted. We will review it and add the card when approved.',
  requestSignIn: 'Sign in to request a new catalog card.',
  cardNotFound: "Can't find your card?",
  requestAddLink: 'Request to add to database',
  submissionEmptyPending: 'No submissions in progress. Scan a card to get started.',
  submissionEmptyReviewed: 'No reviewed submissions yet.',
  submissionDetail: 'Submission',
  player: 'Player',
  year: 'Year',
  sport: 'Sport',
  memorabilia: 'Memorabilia',
  manufacturer: 'Manufacturer',
  team: 'Team',
  cardNumber: 'Card #',
  product: 'Set / product',
  status: 'Status',
  submitted: 'Submitted',
  yourNotes: 'Your notes',
  adminNotes: 'Reviewer notes',
  assetId: 'Asset ID',
  viewVerification: 'View verification'
} as const;
