export const databaseCopy = {
  searchPlaceholder: 'Search cards, players, teams, sets…',
  searchTitle: 'Browse database',
  statsLine: (authenticated: number, total: number) =>
    `${authenticated.toLocaleString()} authenticated · ${total.toLocaleString()} catalog records`,
  ctaObsessionTitle: 'Become a true cardboard detective.',
  ctaObsessionBody:
    'Learn how to evaluate any card’s game-used memorabilia with help from dozens of videos, guides, and resources.',
  pageSubtitle: 'A History of History.',
  browseBySport: 'BROWSE BY SPORT',
  browseByYear: 'BROWSE BY YEAR',
  filter: 'FILTER',
  sort: 'SORT',
  wishlist: 'WISHLIST',
  featuredEmpty: 'No authenticated cards in the catalog yet.',
  recentEmpty: 'No catalog cards yet. Check back after the team publishes records.',
  loadingCatalog: 'Loading catalog records…',
  viewAll: 'VIEW ALL',
  resultsCount: (n: number) => `${n.toLocaleString()} result${n === 1 ? '' : 's'}`,
  authenticatedCopies: 'Authenticated copies',
  noAuthenticatedCopies: 'No authenticated copies yet for this card.',
  authCount: (n: number) => (n === 1 ? '1 authenticated copy' : `${n} authenticated copies`),
  frontLabel: 'FRONT',
  backLabel: 'BACK',
  backToResults: 'BACK TO RESULTS',
  addToWishlist: 'ADD TO WISHLIST',
  onWishlist: 'ON WISHLIST',
  removeFromWishlist: 'REMOVE FROM WISHLIST',
  authenticateSimilar: 'AUTHENTICATE SIMILAR',
  wishlistTitle: 'MY WISHLIST',
  wishlistSubtitle: 'Track cards from saved interest through Most Wanted and the database.',
  wishlistEmpty: 'Your wishlist is empty. Save catalog cards or request missing ones to start demand.',
  wishlistSignIn: 'Sign in to save cards to your wishlist.',
  wishlistAdded: 'Added to your wishlist.',
  wishlistAddedFromMostWanted:
    'Saved to your wishlist. Track its status anytime under Database → Wishlist.',
  wishlistDetailTitle: 'WISHLIST',
  wishlistStatusSaved: 'Saved',
  wishlistStatusRequested: 'Requested',
  wishlistStatusUnderReview: 'Under Review',
  wishlistStatusPromoted: 'Promoted to Most Wanted',
  wishlistStatusEvidenceNeeded: 'Evidence Needed',
  wishlistStatusAdded: 'Added to Database',
  wishlistFilterAll: 'ALL',
  wishlistCtaAuthenticate: 'AUTHENTICATE SIMILAR',
  wishlistCtaViewMostWanted: 'VIEW MOST WANTED',
  wishlistCtaViewCard: 'VIEW DATABASE CARD',
  wishlistCtaRemove: 'REMOVE FROM WISHLIST',
  wishlistMostWantedBadge: 'Most Wanted',
  wishlistJourneyHint: 'Tap a card to see its journey from saved interest to the database.',
  wishlistStorySaved: 'This catalog card is saved. Authenticate a similar copy whenever you are ready.',
  wishlistStoryRequested: 'You asked for this missing card. It is waiting for community demand and review.',
  wishlistStoryUnderReview: "Baxter's team is reviewing this request.",
  wishlistStoryPromoted: 'This request has been promoted to Most Wanted. Community evidence can help solve it.',
  wishlistStoryEvidence: 'Evidence is still needed on the Most Wanted board for this card.',
  wishlistStoryAdded: 'This card is now in the database. Open the catalog record to explore it.',
  wishlistRequestTitle: 'Add to wishlist',
  wishlistRequestSubtitle:
    'We could not find this card in the catalog. Tell us what you are looking for and we will track it for you.',
  wishlistRequestSubmit: 'ADD TO WISHLIST',
  wishlistRequestSuccess: 'Added to your wishlist. We will notify you when this card is in the database.',
  requestCardTitle: 'Request to add',
  requestCardSubtitle: 'Tell us about the card so we can add it to the database.',
  requestSubmit: 'SUBMIT REQUEST',
  requestSuccess: 'Request submitted. We will review it and add the card when approved.',
  requestSignIn: 'Sign in to request a new catalog card.',
  cardNotFound: "Can't find this card?",
  requestAddLink: 'Request it / Add to Wishlist',
  searchEmptyCtaTitle: "Can't find this card?",
  searchEmptyCtaBody: 'Add it to your wishlist so we can track demand and notify you when it lands in the database.',
  filterTitle: 'Filter results',
  sortTitle: 'Sort by',
  authenticatedOnly: 'Authenticated only',
  memorabiliaType: 'Memorabilia type',
  memorabiliaPlaceholder: 'Jersey, patch, bat…',
  applyFilters: 'APPLY',
  clearFilters: 'Clear all',
  submissionEmptyPending: 'No submissions in progress. Scan a card to get started.',
  submissionEmptyReviewed: 'No reviewed submissions yet.',
  submissionDetail: 'Submission',
  player: 'Player',
  year: 'Year',
  sport: 'Sport',
  memorabilia: 'Memorabilia',
  manufacturer: 'Manufacturer',
  team: 'Team',
  cardNumber: 'Card #',
  product: 'Set / product',
  status: 'Status',
  submitted: 'Submitted',
  yourNotes: 'Your notes',
  adminNotes: 'Reviewer notes',
  assetId: 'Asset ID',
  viewVerification: 'View verification',
  cardInfo: 'CARD INFORMATION',
  trending: 'TRENDING THIS WEEK',
  featuredRecords: 'FEATURED RECORDS',
  searchResultsTitle: 'SEARCH RESULTS',
  searchEmpty: 'No matching cards in the catalog.',
  loadMore: 'LOAD MORE',
  myRequestsTitle: 'My card requests',
  myRequestsEmpty: 'You have not requested any cards yet.',
  requestDetailTitle: 'Request status',
  viewAcceptedCard: 'VIEW CATALOG CARD',
  assetDetailTitle: 'Authenticated copy',
  authenticatedAt: 'Authenticated',
  viewCatalogCard: 'VIEW CATALOG CARD',
  verificationTitle: 'Verification',
  verificationOwner: 'Owner',
  verificationStatus: 'Status',
  verificationCatalogSection: 'Catalog card (shared reference)',
  verificationCopyPhotosSection: 'Authenticated copy photos',
  verificationCopyPhotosHint:
    'Submitted by the owner when this physical copy was approved. These do not replace the catalog reference.',
  verificationCopyPhotosEmpty: 'No authenticated copy photos on file.',
  verificationNotFound: 'No asset found for that ID.',
  verificationPublicNotes: 'Notes',
  notificationsTitle: 'Notifications',
  notificationsEmpty: 'No notifications yet.',
  markAllRead: 'Mark all as read',
  cancelSubmission: 'CANCEL SUBMISSION',
  cancellingSubmission: 'CANCELLING…',
  recentlyAdded: 'RECENTLY ADDED',
  recentlyAuthenticated: 'RECENTLY AUTHENTICATED'
} as const;
