export const databaseCopy = {
  searchPlaceholder: 'Search cards, players, teams, sets…',
  searchTitle: 'Browse database',
  statsLine: (authenticated: number, total: number) =>
    `${authenticated.toLocaleString()} authenticated · ${total.toLocaleString()} catalog records`,
  ctaObsessionTitle: 'AUTHENTICATION TAKES OBSESSION.',
  ctaObsessionBody:
    'Learn how to authenticate game-used cards, contribute to the conversation, and win monthly prizes.',
  browseBySport: 'BROWSE BY SPORT',
  browseByYear: 'BROWSE BY YEAR',
  filter: 'FILTER',
  sort: 'SORT',
  wishlist: 'WISHLIST',
  featuredEmpty: 'No authenticated cards in the catalog yet.',
  recentEmpty: 'No catalog cards yet. Check back after the team publishes records.',
  loadingCatalog: 'Loading catalog records…',
  viewAll: 'VIEW ALL',
  resultsCount: (n: number) => `${n.toLocaleString()} result${n === 1 ? '' : 's'}`,
  authenticatedCopies: 'Authenticated copies',
  noAuthenticatedCopies: 'No authenticated copies yet for this card.',
  authCount: (n: number) => (n === 1 ? '1 authenticated copy' : `${n} authenticated copies`),
  frontLabel: 'FRONT',
  backLabel: 'BACK',
  backToResults: 'BACK TO RESULTS',
  addToWishlist: 'ADD TO WISHLIST',
  onWishlist: 'ON WISHLIST',
  removeFromWishlist: 'REMOVE FROM WISHLIST',
  authenticateSimilar: 'AUTHENTICATE SIMILAR',
  wishlistTitle: 'My wishlist',
  wishlistEmpty: 'Your wishlist is empty. Save cards you are hunting for here.',
  wishlistSignIn: 'Sign in to save cards to your wishlist.',
  wishlistAdded: 'Added to your wishlist.',
  wishlistRequestTitle: 'Add to wishlist',
  wishlistRequestSubtitle:
    'We could not find this card in the catalog. Tell us what you are looking for and we will track it for you.',
  wishlistRequestSubmit: 'ADD TO WISHLIST',
  wishlistRequestSuccess: 'Added to your wishlist. We will notify you when this card is in the database.',
  requestCardTitle: 'Request to add',
  requestCardSubtitle: 'Tell us about the card so we can add it to the database.',
  requestSubmit: 'SUBMIT REQUEST',
  requestSuccess: 'Request submitted. We will review it and add the card when approved.',
  requestSignIn: 'Sign in to request a new catalog card.',
  cardNotFound: "Can't find your card?",
  requestAddLink: 'Add to wishlist',
  filterTitle: 'Filter results',
  sortTitle: 'Sort by',
  authenticatedOnly: 'Authenticated only',
  memorabiliaType: 'Memorabilia type',
  memorabiliaPlaceholder: 'Jersey, patch, bat…',
  applyFilters: 'APPLY',
  clearFilters: 'Clear all',
  submissionEmptyPending: 'No submissions in progress. Scan a card to get started.',
  submissionEmptyReviewed: 'No reviewed submissions yet.',
  submissionDetail: 'Submission',
  player: 'Player',
  year: 'Year',
  sport: 'Sport',
  memorabilia: 'Memorabilia',
  manufacturer: 'Manufacturer',
  team: 'Team',
  cardNumber: 'Card #',
  product: 'Set / product',
  status: 'Status',
  submitted: 'Submitted',
  yourNotes: 'Your notes',
  adminNotes: 'Reviewer notes',
  assetId: 'Asset ID',
  viewVerification: 'View verification',
  cardInfo: 'CARD INFORMATION',
  trending: 'TRENDING THIS WEEK',
  featuredRecords: 'FEATURED RECORDS',
  searchResultsTitle: 'SEARCH RESULTS',
  searchEmpty: 'No matching cards in the catalog.',
  loadMore: 'LOAD MORE',
  myRequestsTitle: 'My card requests',
  myRequestsEmpty: 'You have not requested any cards yet.',
  requestDetailTitle: 'Request status',
  viewAcceptedCard: 'VIEW CATALOG CARD',
  assetDetailTitle: 'Authenticated copy',
  authenticatedAt: 'Authenticated',
  viewCatalogCard: 'VIEW CATALOG CARD',
  notificationsTitle: 'Notifications',
  notificationsEmpty: 'No notifications yet.',
  markAllRead: 'Mark all as read',
  cancelSubmission: 'CANCEL SUBMISSION',
  cancellingSubmission: 'CANCELLING…',
  recentlyAdded: 'RECENTLY ADDED',
  recentlyAuthenticated: 'RECENTLY AUTHENTICATED'
} as const;
