import type { EducationTimelineDetail } from '@/lib/education-timeline';

/** Local mirror of the seeded Hobby Timeline — used only when RPC/tables are unavailable. */
export const HISTORY_OF_GAME_USED_FALLBACK: EducationTimelineDetail = {
  id: 'a1000000-0000-4000-8000-000000000001',
  slug: 'a-history-of-game-used-cards',
  title: 'A History of Game-Used Cards',
  summary:
    'Explore the releases, manufacturers, licensing changes, and hobby milestones that shaped modern game-used sports cards.',
  start_year: 1996,
  end_year: 2025,
  cover_image_url: null,
  original_image_url: null,
  pdf_url: null,
  publisher: 'Which Game Used',
  source_type: 'which_game_used',
  rights_status: 'owned',
  difficulty: 'intermediate',
  estimated_read_minutes: 12,
  published_at: '2026-07-24T00:00:00.000Z',
  updated_at: '2026-07-24T00:00:00.000Z',
  events: [
    {
      id: 'a1000000-0000-4000-8000-000000000010',
      sport: 'misc',
      year_start: 1996,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Press Pass',
      product_name: 'NASCAR Burning Rubber',
      event_title: 'First memorabilia cards (NASCAR)',
      short_summary:
        'Press Pass Burning Rubber introduced early game-used memorabilia cards outside the major stick-and-ball sports.',
      detailed_note: null,
      significance: 'first_memorabilia',
      is_first_across_sports: true,
      is_first_in_sport: true,
      display_order: 10,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000020',
      sport: 'baseball',
      year_start: 1996,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Upper Deck',
      product_name: 'Upper Deck',
      event_title: 'First licensed jersey cards',
      short_summary:
        'Upper Deck introduced one of the earliest licensed baseball jersey-card releases.',
      detailed_note: null,
      significance: 'first_licensed_jersey',
      is_first_across_sports: true,
      is_first_in_sport: true,
      display_order: 20,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000021',
      sport: 'baseball',
      year_start: 1999,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Upper Deck',
      product_name: 'Upper Deck',
      event_title: 'First patch cards',
      short_summary: 'Baseball patch cards arrived as an evolution of early jersey inserts.',
      detailed_note: null,
      significance: 'first_patch',
      is_first_across_sports: false,
      is_first_in_sport: true,
      display_order: 21,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000101',
      sport: 'baseball',
      year_start: 1999,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Upper Deck',
      product_name: '500 Club',
      event_title: 'Babe Ruth memorabilia cards',
      short_summary:
        'Upper Deck 500 Club brought Babe Ruth game-used material into mainstream trading cards.',
      detailed_note:
        'Upper Deck\'s "A Piece of History" approach used fragments from historic artifacts for trading cards. Early controversy over "destroying" memorabilia eventually gave way to broader collector acceptance of game-used relic cards.',
      significance: 'historic_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 22,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000102',
      sport: 'baseball',
      year_start: 2001,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Leaf',
      product_name: 'Great American Treasures',
      event_title: 'Historic jersey and memorabilia cards',
      short_summary:
        'Leaf shifted attention from modern stars toward historical legends with jersey and memorabilia cards.',
      detailed_note:
        'The 2001 Leaf Great American Treasures set helped reorient the hobby toward legends such as Hank Aaron, Cy Young, and Ty Cobb, proving historic game-used material could drive premium demand.',
      significance: 'historic_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 30,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000103',
      sport: 'baseball',
      year_start: 2003,
      year_end: 2005,
      is_ongoing: false,
      manufacturer: 'Donruss',
      product_name: 'Babe Ruth Jersey Cards',
      event_title: 'Babe Ruth jersey cards',
      short_summary:
        'Donruss produced multi-year Babe Ruth jersey-card releases from a purchased historic jersey.',
      detailed_note:
        'In 2003 Donruss purchased a 1925 Babe Ruth jersey for $264,210 to create jersey cards. The same era also saw Playoff Absolute "Tools of the Trade" expand multi-relic storytelling around historic equipment.',
      significance: 'historic_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 40,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000024',
      sport: 'baseball',
      year_start: 2016,
      year_end: 2025,
      is_ongoing: true,
      manufacturer: 'Topps',
      product_name: 'Topps Now',
      event_title: 'MLB World Series memorabilia cards',
      short_summary:
        'Topps Now extended World Series memorabilia collecting into near-real-time releases.',
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 50,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000106',
      sport: 'baseball',
      year_start: 2024,
      year_end: 2025,
      is_ongoing: true,
      manufacturer: 'Topps',
      product_name: 'MLB Debut',
      event_title: 'MLB Debut cards',
      short_summary:
        'Topps MLB Debut products connected modern player introductions to memorabilia collecting.',
      detailed_note:
        "Modern Topps MLB Debut cards continue the hobby's pattern of tying game-used material to milestone moments, this time around a player's first big-league appearance.",
      significance: 'modern_milestone',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 60,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000030',
      sport: 'basketball',
      year_start: 1996,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Press Pass',
      product_name: 'NCAA',
      event_title: 'First jersey cards (NCAA)',
      short_summary: 'Press Pass NCAA issued early basketball jersey cards in the college space.',
      detailed_note: null,
      significance: 'first_jersey',
      is_first_across_sports: true,
      is_first_in_sport: true,
      display_order: 70,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000031',
      sport: 'basketball',
      year_start: 1997,
      year_end: null,
      is_ongoing: false,
      manufacturer: "Collector's Edge",
      product_name: "Collector's Edge",
      event_title: 'First memorabilia cards',
      short_summary: "Collector's Edge helped establish early basketball memorabilia inserts.",
      detailed_note: null,
      significance: 'first_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: true,
      display_order: 71,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000032',
      sport: 'basketball',
      year_start: 1997,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Upper Deck',
      product_name: 'Upper Deck',
      event_title: 'First licensed jersey cards',
      short_summary:
        'Upper Deck brought licensed basketball jersey cards into the mainstream checklist era.',
      detailed_note: null,
      significance: 'first_licensed_jersey',
      is_first_across_sports: false,
      is_first_in_sport: true,
      display_order: 72,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000033',
      sport: 'basketball',
      year_start: 1999,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Upper Deck',
      product_name: 'Upper Deck',
      event_title: 'First patch cards',
      short_summary:
        'Basketball patch cards followed licensed jersey inserts as manufacturers chased scarcer swatches.',
      detailed_note: null,
      significance: 'first_patch',
      is_first_across_sports: false,
      is_first_in_sport: true,
      display_order: 73,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000034',
      sport: 'basketball',
      year_start: 2000,
      year_end: 2006,
      is_ongoing: false,
      manufacturer: 'Topps',
      product_name: 'Topps',
      event_title: 'First championship jersey cards',
      short_summary: 'Topps issued multi-year championship jersey cards tied to title runs.',
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: true,
      display_order: 80,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000035',
      sport: 'basketball',
      year_start: 2002,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Upper Deck',
      product_name: 'Upper Deck',
      event_title: 'First Logoman cards',
      short_summary:
        'An important milestone in premium game-used card design and a foundation of the modern Logoman market.',
      detailed_note: null,
      significance: 'first_logoman',
      is_first_across_sports: true,
      is_first_in_sport: true,
      display_order: 90,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000104',
      sport: 'basketball',
      year_start: 2003,
      year_end: 2008,
      is_ongoing: false,
      manufacturer: 'Upper Deck',
      product_name: 'Exquisite Collection',
      event_title: 'Notable autograph and game-used Exquisite releases',
      short_summary:
        'Upper Deck Exquisite defined the luxury end of basketball memorabilia collecting.',
      detailed_note:
        'The 2003–04 Upper Deck Exquisite Collection pioneered the high-end luxury market and made the Logoman card a premier chase item, reshaping what collectors expected from premium game-used products.',
      significance: 'premium_luxury',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 100,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000037',
      sport: 'basketball',
      year_start: 2009,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Panini',
      product_name: 'NBA license',
      event_title: 'Panini acquires DLP and exclusive NBA license',
      short_summary:
        "Panini's exclusive NBA licensing reshaped who could produce basketball memorabilia cards.",
      detailed_note: null,
      significance: 'licensing_change',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 110,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000038',
      sport: 'basketball',
      year_start: 2012,
      year_end: 2015,
      is_ongoing: false,
      manufacturer: 'Panini',
      product_name: 'NBA Finals',
      event_title: 'NBA Finals memorabilia cards',
      short_summary: 'Panini issued Finals-tied memorabilia during its early exclusive-license years.',
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 120,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000039',
      sport: 'basketball',
      year_start: 2013,
      year_end: 2019,
      is_ongoing: false,
      manufacturer: 'Panini',
      product_name: 'NBA Finals booklets',
      event_title: 'First NBA Finals jersey, patch, and logo booklets',
      short_summary:
        'Panini expanded Finals memorabilia into booklet formats featuring jersey, patch, and logo pieces.',
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: true,
      is_first_in_sport: true,
      display_order: 130,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-00000000003a',
      sport: 'basketball',
      year_start: 2015,
      year_end: 2018,
      is_ongoing: false,
      manufacturer: 'Panini',
      product_name: 'NBA Finals',
      event_title: 'NBA Finals jersey, patch, and logo cards',
      short_summary:
        "Single-card Finals jersey, patch, and logo releases continued Panini's championship program.",
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 140,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000105',
      sport: 'basketball',
      year_start: 2023,
      year_end: 2025,
      is_ongoing: false,
      manufacturer: 'Panini',
      product_name: 'NBA Finals',
      event_title: 'Finals jersey cards',
      short_summary:
        'Later-cycle Panini Finals jersey cards arrived as licensing and demand patterns shifted again.',
      detailed_note:
        'After a decade of Panini dominance in basketball card production, market values and collector demand shifted as licensing rights changed—making late-cycle Finals memorabilia an important case study in how licenses move the hobby.',
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 150,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000040',
      sport: 'football',
      year_start: 1996,
      year_end: null,
      is_ongoing: false,
      manufacturer: "Collector's Edge",
      product_name: "Collector's Edge",
      event_title: 'First championship memorabilia cards (Super Bowl)',
      short_summary:
        "Collector's Edge tied early football memorabilia cards to Super Bowl championship material.",
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: true,
      is_first_in_sport: true,
      display_order: 160,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000041',
      sport: 'football',
      year_start: 1996,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Upper Deck',
      product_name: 'Upper Deck',
      event_title: 'First licensed jersey cards',
      short_summary:
        'Upper Deck introduced licensed football jersey cards in the same formative mid-1990s window.',
      detailed_note: null,
      significance: 'first_licensed_jersey',
      is_first_across_sports: true,
      is_first_in_sport: true,
      display_order: 161,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000042',
      sport: 'football',
      year_start: 1998,
      year_end: 2000,
      is_ongoing: false,
      manufacturer: 'Playoff',
      product_name: 'Playoff',
      event_title: 'Super Bowl memorabilia cards',
      short_summary: 'Playoff issued multi-year Super Bowl memorabilia cards at the turn of the century.',
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 170,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000043',
      sport: 'football',
      year_start: 1999,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Upper Deck',
      product_name: 'Upper Deck',
      event_title: 'First patch cards',
      short_summary:
        'Football patch cards followed licensed jersey releases as manufacturers sought scarcer game-used windows.',
      detailed_note: null,
      significance: 'first_patch',
      is_first_across_sports: false,
      is_first_in_sport: true,
      display_order: 171,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000044',
      sport: 'football',
      year_start: 2000,
      year_end: 2008,
      is_ongoing: false,
      manufacturer: 'Topps',
      product_name: 'Topps',
      event_title: 'Super Bowl MVP autograph and memorabilia cards',
      short_summary:
        'Topps connected Super Bowl MVP recognition to multi-year autograph and memorabilia releases.',
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 180,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000045',
      sport: 'football',
      year_start: 2002,
      year_end: 2006,
      is_ongoing: false,
      manufacturer: 'Playoff',
      product_name: 'Playoff',
      event_title: 'Super Bowl memorabilia cards',
      short_summary: 'Playoff continued Super Bowl memorabilia programs through the mid-2000s.',
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 190,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000046',
      sport: 'football',
      year_start: 2009,
      year_end: null,
      is_ongoing: false,
      manufacturer: 'Panini',
      product_name: 'NFL license',
      event_title: 'Panini acquires DLP and NFL license',
      short_summary:
        "Panini's NFL licensing deal redirected who could produce major football memorabilia products.",
      detailed_note: null,
      significance: 'licensing_change',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 200,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000047',
      sport: 'football',
      year_start: 2011,
      year_end: 2018,
      is_ongoing: false,
      manufacturer: 'Panini',
      product_name: 'Panini',
      event_title: 'Super Bowl memorabilia cards',
      short_summary: 'Panini issued a long Super Bowl memorabilia run under its NFL license.',
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 210,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    },
    {
      id: 'a1000000-0000-4000-8000-000000000048',
      sport: 'football',
      year_start: 2011,
      year_end: 2012,
      is_ongoing: false,
      manufacturer: 'Topps',
      product_name: 'Five Star',
      event_title: 'Super Bowl memorabilia cards',
      short_summary:
        "Topps Five Star offered a short Super Bowl memorabilia window alongside Panini's broader program.",
      detailed_note: null,
      significance: 'championship_memorabilia',
      is_first_across_sports: false,
      is_first_in_sport: false,
      display_order: 220,
      related_card_ids: [],
      related_discussion_ids: [],
      related_most_wanted_ids: []
    }
  ],
  sources: [
    {
      id: 'src-1',
      timeline_event_id: 'a1000000-0000-4000-8000-000000000101',
      citation_number: 1,
      source_title: 'Upper Deck 500 Club / A Piece of History — Babe Ruth memorabilia cards',
      source_url: null,
      author: 'Which Game Used research synthesis',
      published_on: '1999',
      accessed_on: '2026-07-24',
      source_type: 'research_note',
      rights_or_permission_note:
        'Seeded from owned/permitted Which Game Used timeline infographic. Confirm rights before production marketing.'
    },
    {
      id: 'src-2',
      timeline_event_id: 'a1000000-0000-4000-8000-000000000102',
      citation_number: 2,
      source_title: 'Leaf Great American Treasures — historic jersey and memorabilia cards',
      source_url: null,
      author: 'Which Game Used research synthesis',
      published_on: '2001',
      accessed_on: '2026-07-24',
      source_type: 'research_note',
      rights_or_permission_note:
        'Seeded from owned/permitted Which Game Used timeline infographic. Confirm rights before production marketing.'
    },
    {
      id: 'src-3',
      timeline_event_id: 'a1000000-0000-4000-8000-000000000103',
      citation_number: 3,
      source_title:
        'Donruss Babe Ruth jersey cards and Playoff Absolute Tools of the Trade context',
      source_url: null,
      author: 'Which Game Used research synthesis',
      published_on: '2003–2005',
      accessed_on: '2026-07-24',
      source_type: 'research_note',
      rights_or_permission_note:
        'Seeded from owned/permitted Which Game Used timeline infographic. Confirm rights before production marketing.'
    },
    {
      id: 'src-4',
      timeline_event_id: 'a1000000-0000-4000-8000-000000000104',
      citation_number: 4,
      source_title: 'Upper Deck Exquisite Collection and the Logoman chase',
      source_url: null,
      author: 'Which Game Used research synthesis',
      published_on: '2003–2008',
      accessed_on: '2026-07-24',
      source_type: 'research_note',
      rights_or_permission_note:
        'Seeded from owned/permitted Which Game Used timeline infographic. Confirm rights before production marketing.'
    },
    {
      id: 'src-5',
      timeline_event_id: 'a1000000-0000-4000-8000-000000000105',
      citation_number: 5,
      source_title: 'Panini NBA Finals jersey cards and licensing-era market shifts',
      source_url: null,
      author: 'Which Game Used research synthesis',
      published_on: '2023–2025',
      accessed_on: '2026-07-24',
      source_type: 'research_note',
      rights_or_permission_note:
        'Seeded from owned/permitted Which Game Used timeline infographic. Confirm rights before production marketing.'
    },
    {
      id: 'src-6',
      timeline_event_id: 'a1000000-0000-4000-8000-000000000106',
      citation_number: 6,
      source_title: 'Topps MLB Debut memorabilia cards',
      source_url: null,
      author: 'Which Game Used research synthesis',
      published_on: '2024–2025',
      accessed_on: '2026-07-24',
      source_type: 'research_note',
      rights_or_permission_note:
        'Seeded from owned/permitted Which Game Used timeline infographic. Confirm rights before production marketing.'
    }
  ]
};
